language: r
sudo: false
cache: packages

r:
 - release
 - devel

os:
  - linux
  - osx
  
env:
  matrix: 
    - CXX=clang++ USE_CXX11=1
    
warnings_are_errors: true

after_failure:
- ./travis-tool.sh dump_logs

r_check_args: "--as-cran"
